### ISSUE TITLE
Investigate recurring "no matching index found" error in logs

### ISSUE THREAD

**Issue by gunsch** [adhocteam/nytimes-library#5]
Noticed this occurring frequently in the logs. Looks like a missing Datastore index?

```{ message:
   '9 FAILED_PRECONDITION: no matching index found. recommended index is:\n- kind: LibraryViewTeam\n  properties:\n  - name: userId\n  - name: lastViewedAt\n    direction: desc\n',
  stack:
   'Error: 9 FAILED_PRECONDITION: no matching index found. recommended index is:\n- kind: LibraryViewTeam\n  properties:\n  - name: userId\n  - name: lastViewedAt\n    direction: desc\n\n    at Object.callErrorFromStatus (/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:30:26)\n    at Http2CallStream.call.on (/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:96:33)\n    at Http2CallStream.emit (events.js:203:15)\n    at process.nextTick (/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:100:22)\n    at process._tickCallback (internal/process/next_tick.js:61:11)',
  code: 9,
  details:
   'no matching index found. recommended index is:\n- kind: LibraryViewTeam\n  properties:\n  - name: userId\n  - name: lastViewedAt\n    direction: desc\n',
  metadata: { internalRepr: {}, options: {} },
  note:
   'Exception occurred in retry method that was not classified as transient' }
```

**Comment by gunsch** [comment]
duplicate of #8
